const pedidos = [
    {
        id: 1,
        nome: 'william',
        itens: ['batata frita', 'coca cola'],
        numeroPedido: 5,
        guiche: 1,
        data: '30/04/2021',
        hora: '12:12',
        status: 'andamento',
    },
    {
        id: 2,
        nome: 'william',
        itens: ['hotdog', 'coca cola'],
        numeroPedido: 6,
        guiche: 1,
        data: '01/05/2021',
        hora: '12:14',
        status: 'andamento',
    },
    {
        id: 3,
        nome: 'william',
        itens: ['hotdog', 'delvalle'],
        numeroPedido: 7,
        guiche: 1,
        data: '01/05/2021',
        hora: '12:16',
        status: 'andamento',
    },
    {
        id: 4,
        nome: 'william',
        itens: ['batata frita cheddar e bacon', 'coca cola'],
        numeroPedido: 8,
        guiche: 1,
        data: '01/05/2021',
        hora: '12:18',
        status: 'andamento',
    },
    {
        id: 5,
        nome: 'william',
        itens: ['hotdog com chile', 'coca cola'],
        numeroPedido: 9,
        guiche: 1,
        data: '08/05/2021',
        hora: '13:00',
        status: 'andamento',
    },
    {
        id: 6,
        nome: 'william',
        itens: ['hotdog GG', 'coca cola'],
        numeroPedido: 10,
        guiche: 1,
        data: '08/05/2021',
        hora: '13:10',
        status: 'andamento',
    },
    {
        id: 7,
        nome: 'william',
        itens: ['hotdog com chile', 'coca cola'],
        numeroPedido: 11,
        guiche: 1,
        data: '08/05/2021',
        hora: '13:20',
        status: 'andamento',
    },
    {
        id: 8,
        nome: 'william',
        itens: ['hotdog especial', 'coca cola'],
        numeroPedido: 12,
        guiche: 1,
        data: '09/05/2021',
        hora: '13:20',
        status: 'andamento',
    }
]

module.exports = pedidos;